[2025-10-12T23:45:39.873+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:45:39.874+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:45:39.916+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:45:39.916+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:45:39.965+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:44:30.092215+00:00 [queued]>
[2025-10-12T23:45:39.971+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:44:30.092215+00:00 [queued]>
[2025-10-12T23:45:39.972+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2025-10-12T23:45:39.981+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_rig_count_pipeline> on 2025-10-12 23:44:30.092215+00:00
[2025-10-12T23:45:39.987+0000] {standard_task_runner.py:57} INFO - Started process 11899 to run task
[2025-10-12T23:45:39.991+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_pipeline', 'bronze_rig_count_pipeline', 'manual__2025-10-12T23:44:30.092215+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/ETL_pipeline.py', '--cfg-path', '/tmp/tmpw2si3m2t']
[2025-10-12T23:45:39.994+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask bronze_rig_count_pipeline
[2025-10-12T23:45:40.038+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:45:40.038+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:44:30.092215+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:45:40.040+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:44:30.092215+00:00 [running]> on host f22a895b55de
[2025-10-12T23:45:40.109+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bech' AIRFLOW_CTX_DAG_ID='ETL_pipeline' AIRFLOW_CTX_TASK_ID='bronze_rig_count_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T23:44:30.092215+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T23:44:30.092215+00:00'
[2025-10-12T23:45:40.111+0000] {bronze_layer.py:123} INFO - Starting bronze layer data ingestion...
[2025-10-12T23:45:40.111+0000] {logging_mixin.py:151} INFO - Getting rig count data...
[2025-10-12T23:45:41.786+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:329 UserWarning: Unknown extension is not supported and will be removed
[2025-10-12T23:45:41.813+0000] {logging_mixin.py:151} INFO - Successfully loaded Excel file. Shape: (16503, 12)
[2025-10-12T23:45:41.829+0000] {base.py:73} INFO - Using connection ID 'oil_gas_conn' for task execution.
[2025-10-12T23:45:41.829+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-10-12T23:45:41.830+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-12T23:45:41.830+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2025-10-12T23:45:42.569+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-10-12T23:45:42.661+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:42.662+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:42.664+0000] {sql.py:418} INFO - Running statement: USE WAREHOUSE COMPUTE_WH, parameters: None
[2025-10-12T23:45:42.664+0000] {cursor.py:804} INFO - query: [USE WAREHOUSE COMPUTE_WH]
[2025-10-12T23:45:42.765+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:42.766+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:42.767+0000] {sql.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:42.767+0000] {snowflake.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:42.768+0000] {snowflake.py:428} INFO - Snowflake query id: 01bfabb1-0106-9ab0-000b-be53002825fa
[2025-10-12T23:45:42.768+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-10-12T23:45:42.852+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:42.853+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:42.853+0000] {connection.py:640} INFO - closed
[2025-10-12T23:45:42.894+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2025-10-12T23:45:42.952+0000] {base.py:73} INFO - Using connection ID 'oil_gas_conn' for task execution.
[2025-10-12T23:45:42.954+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-10-12T23:45:42.954+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-12T23:45:43.385+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-10-12T23:45:43.592+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:43.593+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:43.594+0000] {sql.py:418} INFO - Running statement: USE DATABASE OILGAS_DB, parameters: None
[2025-10-12T23:45:43.594+0000] {cursor.py:804} INFO - query: [USE DATABASE OILGAS_DB]
[2025-10-12T23:45:43.693+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:43.694+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:43.694+0000] {sql.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:43.695+0000] {snowflake.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:43.696+0000] {snowflake.py:428} INFO - Snowflake query id: 01bfabb1-0106-a44d-000b-be530029a102
[2025-10-12T23:45:43.696+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-10-12T23:45:43.801+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:43.802+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:43.803+0000] {connection.py:640} INFO - closed
[2025-10-12T23:45:43.853+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2025-10-12T23:45:43.910+0000] {base.py:73} INFO - Using connection ID 'oil_gas_conn' for task execution.
[2025-10-12T23:45:43.911+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-10-12T23:45:43.911+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-12T23:45:44.832+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-10-12T23:45:44.915+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:44.916+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:44.923+0000] {sql.py:418} INFO - Running statement: USE SCHEMA raw, parameters: None
[2025-10-12T23:45:44.924+0000] {cursor.py:804} INFO - query: [USE SCHEMA raw]
[2025-10-12T23:45:45.009+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:45.010+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:45.010+0000] {sql.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:45.011+0000] {snowflake.py:427} INFO - Rows affected: 1
[2025-10-12T23:45:45.011+0000] {snowflake.py:428} INFO - Snowflake query id: 01bfabb1-0106-a44d-000b-be530029a106
[2025-10-12T23:45:45.011+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-10-12T23:45:45.085+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:45.086+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:45.087+0000] {connection.py:640} INFO - closed
[2025-10-12T23:45:45.132+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2025-10-12T23:45:45.183+0000] {bronze_layer.py:84} INFO - Storing data in bronze layer...
[2025-10-12T23:45:45.191+0000] {base.py:73} INFO - Using connection ID 'oil_gas_conn' for task execution.
[2025-10-12T23:45:45.191+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-10-12T23:45:45.192+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-12T23:45:45.870+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-10-12T23:45:45.953+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:45.954+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-10-12T23:45:45.954+0000] {sql.py:418} INFO - Running statement: truncate table if exists BRONZE.{BRONZE_TABLE};, parameters: None
[2025-10-12T23:45:45.955+0000] {cursor.py:804} INFO - query: [truncate table if exists BRONZE.{BRONZE_TABLE};]
[2025-10-12T23:45:46.055+0000] {cursor.py:817} INFO - query execution done
[2025-10-12T23:45:46.064+0000] {connection.py:640} INFO - closed
[2025-10-12T23:45:46.111+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2025-10-12T23:45:46.172+0000] {bronze_layer.py:148} ERROR - Bronze layer ingestion failed: 001003 (42000): 01bfabb1-0106-9b14-000b-be530028d37e: SQL compilation error:
syntax error line 1 at position 32 unexpected '{'.
[2025-10-12T23:45:46.173+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipeline/bronze_layer.py", line 137, in bronze_etl
    store_rig_data_snowflake(raw_data, sf_hook)
  File "/opt/airflow/pipeline/bronze_layer.py", line 87, in store_rig_data_snowflake
    sf_hook.run("""
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 415, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01bfabb1-0106-9b14-000b-be530028d37e: SQL compilation error:
syntax error line 1 at position 32 unexpected '{'.
[2025-10-12T23:45:46.182+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_pipeline, task_id=bronze_rig_count_pipeline, execution_date=20251012T234430, start_date=20251012T234539, end_date=20251012T234546
[2025-10-12T23:45:46.195+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task bronze_rig_count_pipeline (001003 (42000): 01bfabb1-0106-9b14-000b-be530028d37e: SQL compilation error:
syntax error line 1 at position 32 unexpected '{'.; 11899)
[2025-10-12T23:45:46.224+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-12T23:45:46.235+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
