[2025-10-13T03:49:23.163+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509
[2025-10-13T03:49:23.164+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake'
[2025-10-13T03:49:23.205+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509
[2025-10-13T03:49:23.205+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake'
[2025-10-13T03:49:23.271+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_pipeline.load_counties_to_snowflake manual__2025-10-13T03:49:20.505940+00:00 [queued]>
[2025-10-13T03:49:23.278+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_pipeline.load_counties_to_snowflake manual__2025-10-13T03:49:20.505940+00:00 [queued]>
[2025-10-13T03:49:23.279+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-10-13T03:49:23.295+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_counties_to_snowflake> on 2025-10-13 03:49:20.505940+00:00
[2025-10-13T03:49:23.305+0000] {standard_task_runner.py:57} INFO - Started process 18547 to run task
[2025-10-13T03:49:23.310+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_pipeline', 'load_counties_to_snowflake', 'manual__2025-10-13T03:49:20.505940+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/ETL_pipeline.py', '--cfg-path', '/tmp/tmpunvk5ve7']
[2025-10-13T03:49:23.315+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask load_counties_to_snowflake
[2025-10-13T03:49:23.376+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509
[2025-10-13T03:49:23.377+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-13T03:49:20.505940+00:00/task_id=load_counties_to_snowflake'
[2025-10-13T03:49:23.379+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_pipeline.load_counties_to_snowflake manual__2025-10-13T03:49:20.505940+00:00 [running]> on host f22a895b55de
[2025-10-13T03:49:23.452+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bech' AIRFLOW_CTX_DAG_ID='ETL_pipeline' AIRFLOW_CTX_TASK_ID='load_counties_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-13T03:49:20.505940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-13T03:49:20.505940+00:00'
[2025-10-13T03:49:23.453+0000] {bronze_counties_layer.py:255} INFO - Starting bronze layer data ingestion for US Counties Centroids...
[2025-10-13T03:49:23.463+0000] {bronze_counties_layer.py:69} INFO - Creating Snowflake connection...
[2025-10-13T03:49:23.464+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-10-13T03:49:23.465+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-13T03:49:23.465+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2025-10-13T03:49:24.247+0000] {bronze_counties_layer.py:82} INFO - Snowflake connection established successfully
[2025-10-13T03:49:24.248+0000] {bronze_counties_layer.py:158} INFO - Uploading CSV file to stage US_Counties_Centroids...
[2025-10-13T03:49:24.249+0000] {cursor.py:804} INFO - query: [PUT file:///opt/***/input/US_Counties_Centroids.csv @US_Counties_Centroids O...]
[2025-10-13T03:49:24.349+0000] {cursor.py:817} INFO - query execution done
[2025-10-13T03:49:24.361+0000] {bronze_counties_layer.py:174} ERROR - Error uploading to stage: 002003 (02000): 01bfaca5-0106-a48a-000b-be530029d14a: SQL compilation error:
Stage 'OILGAS_DB.RAW.US_COUNTIES_CENTROIDS' does not exist or not authorized.
[2025-10-13T03:49:24.362+0000] {bronze_counties_layer.py:278} ERROR - ‚ùå Bronze layer ingestion failed: 002003 (02000): 01bfaca5-0106-a48a-000b-be530029d14a: SQL compilation error:
Stage 'OILGAS_DB.RAW.US_COUNTIES_CENTROIDS' does not exist or not authorized.
[2025-10-13T03:49:24.362+0000] {connection.py:640} INFO - closed
[2025-10-13T03:49:24.411+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2025-10-13T03:49:24.482+0000] {bronze_counties_layer.py:284} INFO - Snowflake connection closed
[2025-10-13T03:49:24.484+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipeline/bronze_counties_layer.py", line 267, in counties_bronze_etl
    upload_csv_to_stage(cur, CSV_FILE_PATH, SNOWFLAKE_TABLE)
  File "/opt/airflow/pipeline/bronze_counties_layer.py", line 166, in upload_csv_to_stage
    cur.execute(put_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01bfaca5-0106-a48a-000b-be530029d14a: SQL compilation error:
Stage 'OILGAS_DB.RAW.US_COUNTIES_CENTROIDS' does not exist or not authorized.
[2025-10-13T03:49:24.494+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_pipeline, task_id=load_counties_to_snowflake, execution_date=20251013T034920, start_date=20251013T034923, end_date=20251013T034924
[2025-10-13T03:49:24.518+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task load_counties_to_snowflake (002003 (02000): 01bfaca5-0106-a48a-000b-be530029d14a: SQL compilation error:
Stage 'OILGAS_DB.RAW.US_COUNTIES_CENTROIDS' does not exist or not authorized.; 18547)
[2025-10-13T03:49:24.566+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-13T03:49:24.586+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
